name: Backend User Story
description: History template for backend user story
title: "[Backend]: "
labels: ["user-story"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: Descreva a sua historia aqui.
    validations:
      required: true
