# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: PoE Selling frontend CI

on:
  push:
    paths:
      - "./frontend/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "./frontend/**"
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4.1.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 21.x
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - run: npm ci
      working-directory: ./frontend
    - run: npm run build --if-present
      working-directory: ./frontend
    - run: npm run lint
      working-directory: ./frontend
